Allow configuring user agent / other default options
algolia/algoliasearch-rails pull request #438
Opened 2023-10-06 02:52 UTC by bagedevimo

| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes (ish)
| New feature?      | yes (ish)
| BC breaks?        | yes (ish?)    
| Need Doc update   | yes

## Describe your change
Currently the default options are merged into the user-supplied configuration which means that any user supplied configuration for the user agent would be overwritten.

This could technically be described as a breaking change, but only if the user was relying on a somewhat odd behaviour. They'd have to set a configuration value then rely on it being overwritten. I can't think of a use case for that, but if someone was doing something interesting with a proxy that sniffs user-agent, and had done the above they might technically have a breakage. Otherwise, I'd usually describe this as a bugfix.

## What problem is this fixing?

This means users can supply a different user agent (if they so choose) but also other configuration options could be moved to have defaults that are then easily overridable by users.

2023-10-06 02:58 UTC, bagedevimo commented
The context on this, is that while authoring another change (https://github.com/algolia/algoliasearch-rails/pull/439) I thought this might be a better approach that also fits with the longer-term goals of #85. 

I thought this change was significant / controversial enough (potential breaking change, see above) that'd it'd be worth discussion separately from the main change in #439.

2023-10-17 20:21 UTC, bagedevimo commented
Apologies for the delay - I've just updated the MR to address these issues, let me know what you think of the approach :)

2023-10-17 20:22 UTC, bagedevimo commented
Oh, I should mention, I've left the default_configuration hash in place as it seems like a good place to put the options described in #85

2023-10-29 21:59 UTC, bagedevimo commented
Hi @DevinCodes, sorry for the bump - just wondering if you've had a chance to take a peek at this and have any further feedback?

2023-11-06 15:26 UTC, DevinCodes requested changes
Hey @bagedevimo ,

Sorry, I was on vacation! The PR looks good, I just one small suggestion 😄

2023-11-06 22:17 UTC, bagedevimo commented
Thanks! Hope you had a lovely vacation. I've updated that with an amend commit and force-pushed now.

2023-11-07 08:13 UTC, DevinCodes approved these changes
Thank you again! 💙

2023-11-07 08:14 UTC, merged